# -*- coding: utf-8 -*-
"""Webtoons.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_nesNK6Igj2FjCAzz84mQEg2gnUasBGA

*   **Realizando a instalação de dependências necessárias**
"""

!pip install kora -q

"""* **Importando a lista de autores de Webtoons em txt**"""

from kora.selenium import wd
import csv
autores_txt = open("autores_webtoons.txt", "r")
autores_webtoons = [x.strip() for x in autores_txt.readlines()]
#print(autores_webtoons)

"""*   **Realizando pesquisa por webtoons pelo nome do autor**




"""

webtoons_list = list()
erros = list()

for author in autores_webtoons:
  try:
    wd.get(f'https://www.webtoons.com/en/search?searchMode=AUTHOR&keyword={author}')
    wd.find_element_by_class_name('challenge_item').click()
  except:
    print(author)
    erros.append(author)
  else:
    name = wd.find_elements_by_class_name('_challengeTitle')[0].text
    info = [wd.find_element_by_xpath(f'//*[@id="_asideDetail"]/ul/li[{i+1}]') for i in range(3)]
    sub, views, rate = [i.find_element_by_tag_name('em').text for i in info]
    genre = wd.find_elements_by_class_name('genre')
    genre = [g.text for g in genre]
    author = wd.find_elements_by_xpath('//*[@id="content"]/div[2]/div[1]/div[1]/span')[0].text[:-11]
    webtoons_list.append([author, name, sub, views, rate, '|'.join(genre)])

header = ["Author", "Webtoon", "Subscribed", "View", "Rate", "Genre"]
with open('webtoons.csv', 'w', encoding='UTF8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(webtoons_list)
  
print(erros)

import pandas as pd
data = pd.read_csv('webtoons.csv')
data